# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider :libvirt do |server|
    server.memory = 2048
    server.cpus = 2
  end

  config.vm.define "master" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname = "master"
    subconfig.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.define "node1" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname = "node1"
    subconfig.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.define "node2" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname = "node2"
    subconfig.vm.network "private_network", ip: "192.168.33.12"
  end

  #config.vm.provision "shell", inline: <<-SHELL
  #  yum update -y
  #SHELL
end
