# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |server|
    server.memory = 10240
    server.cpus = 8
  end

  config.vm.define "master" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname = "master"
    subconfig.vm.network "private_network", ip: "192.168.23.10"
  end

  config.vm.define "node1" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname = "node1"
    subconfig.vm.network "private_network", ip: "192.168.23.11"
  end

  config.vm.define "node2" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname = "node2"
    subconfig.vm.network "private_network", ip: "192.168.23.12"
  end

  config.vm.define "node3" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname = "node2"
    subconfig.vm.network "private_network", ip: "192.168.23.13"
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum clean all
    yum install socat -y
    yum install net-tools -y
  SHELL
end
