# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |server|
    server.memory = 16384
    server.cpus = 8
  end

  config.vm.define "node1" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname = "node1"
    subconfig.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.define "node2" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname = "node2"
    subconfig.vm.network "private_network", ip: "192.168.33.12"
  end

  config.vm.define "node3" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname = "node3"
    subconfig.vm.network "private_network", ip: "192.168.33.13"
  end

  config.vm.provision "shell", inline: <<-SHELL
    export https_proxy=http://10.100.17.37:80
    setenforce 0
    sed -i s/SELINUX=enforcing/SELINUX=disabled/g /etc/sysconfig/selinux
    yum clean all
    yum install socat -y
    yum install net-tools -y
    yum install -y yum-utils device-mapper-persistent-data lvm2
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    echo "HTTPS_PROXY=http://10.100.17.37:80" > /etc/sysconfig/docker
    echo "NO_PROXY=10.100.47.240" >> /etc/sysconfig/docker
    yum install -y docker-ce
    sed -i "s/\[Service\]/\[Service\]\nEnvironmentFile=-\/etc\/sysconfig\/docker/g" /lib/systemd/system/docker.service
    systemctl daemon-reload
    systemctl restart docker
    systemctl enable docker
    echo "net.bridge.bridge-nf-call-ip6tables = 1" > /etc/sysctl.d/k8s.conf
    echo "net.bridge.bridge-nf-call-iptables = 1" >>  /etc/sysctl.d/k8s.conf
    sysctl --system
    echo "[kubernetes]" > /etc/yum.repos.d/kubernetes.repo
    echo "name=Kubernetes" >> /etc/yum.repos.d/kubernetes.repo
    echo "baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64" >> /etc/yum.repos.d/kubernetes.repo
    echo "enabled=1" >> /etc/yum.repos.d/kubernetes.repo
    echo "gpgcheck=1" >> /etc/yum.repos.d/kubernetes.repo
    echo "repo_gpgcheck=1" >> /etc/yum.repos.d/kubernetes.repo
    echo "gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg" >> /etc/yum.repos.d/kubernetes.repo
    yum install -y kubelet-1.9.3-0 kubeadm kubectl
    sed -i "s/cgroup-driver=systemd/cgroup-driver=cgroupfs/g" /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    systemctl daemon-reload
    systemctl enable kubelet && systemctl start kubelet
    swapoff --all
    sed -i 's/[^#]\(.*swap.*\)/# \1/' /etc/fstab
    unset https_proxy
  SHELL
end
